<script setup lang="ts">
import LauncherWindow from "./components/launcher/LauncherWindow.vue";
import SettingsWindow from "./components/settings/SettingsWindow.vue";
import { useAppCompositionRoot } from "./composables/app/useAppCompositionRoot";

const {
  isSettingsWindow,
  query,
  executing,
  executionFeedbackMessage,
  executionFeedbackTone,
  searchShellStyle,
  stagingExpanded,
  drawerOpen,
  drawerViewportHeight,
  drawerFloorViewportHeight,
  drawerFillerHeight,
  keyboardHints,
  filteredResults,
  activeIndex,
  stagedFeedbackCommandId,
  stagedCommands,
  stagingDrawerState,
  stagingHints,
  stagingListShouldScroll,
  stagingListMaxHeight,
  focusZone,
  stagingActiveIndex,
  pendingCommand,
  pendingArgs,
  pendingArgValues,
  pendingSubmitHint,
  pendingSubmitMode,
  safetyDialog,
  navCurrentPage,
  navCanGoBack,
  navPushPage,
  navPopPage,
  navResetToSearch,
  navStack,
  setSearchShellRef,
  setSearchInputRef,
  setDrawerRef,
  setStagingPanelRef,
  setStagingListRef,
  setResultButtonRef,
  setParamInputRef,
  onQueryInput,
  stageResult,
  executeResult,
  toggleStaging,
  onStagingDragStart,
  onStagingDragOver,
  onStagingDragEnd,
  onFocusStagingIndex,
  removeStagedCommand,
  updateStagedArg,
  clearStaging,
  executeStaged,
  submitParamInput,
  cancelParamInput,
  updatePendingArgValue,
  confirmSafetyExecution,
  cancelSafetyExecution,
  settingsNavItems,
  settingsRoute,
  hotkeyGlobalFields,
  hotkeySearchFields,
  hotkeyQueueFields,
  getHotkeyValue,
  isHotkeyRecording,
  getHotkeyDisplay,
  availableTerminals,
  terminalLoading,
  terminalDropdownOpen,
  terminalFocusIndex,
  defaultTerminal,
  language,
  autoCheckUpdate,
  launchAtLogin,
  selectedTerminalOption,
  selectedTerminalPath,
  languageOptions,
  appVersion,
  runtimePlatform,
  updateStatus,
  commandRows,
  commandSummary,
  commandLoadIssues,
  commandFilteredCount,
  commandView,
  commandSourceOptions,
  commandStatusOptions,
  commandCategoryOptions,
  commandOverrideOptions,
  commandIssueOptions,
  commandSortOptions,
  commandDisplayModeOptions,
  commandSourceFileOptions,
  commandGroups,
  settingsError,
  settingsErrorRoute,
  hotkeyErrorFields,
  hotkeyErrorPrimaryField,
  hotkeyErrorMessage,
  settingsSaved,
  settingsCloseConfirmOpen,
  cancelSettingsCloseConfirm,
  discardUnsavedSettingsChanges,
  navigateSettings,
  applyHotkeyChange,
  toggleTerminalDropdown,
  selectTerminalOption,
  selectLanguageOption,
  setAutoCheckUpdate,
  setLaunchAtLogin,
  toggleCommandEnabled,
  setFilteredCommandsEnabled,
  updateCommandView,
  resetCommandFilters,
  checkUpdate,
  downloadUpdate,
  openHomepage,
  closeSettingsWindow,
  hideMainWindow,
  saveSettings,
  windowOpacity,
  theme,
  blurEnabled,
  themes,
  setWindowOpacity,
  setTheme,
  setBlurEnabled,
  setExecutionFeedback
} = useAppCompositionRoot();

async function confirmSettings(): Promise<void> {
  await saveSettings();
  if (settingsError.value || !settingsSaved.value) {
    return;
  }
  closeSettingsWindow();
}

function navigateToSettingsError(): void {
  if (!settingsErrorRoute.value) {
    return;
  }
  navigateSettings(settingsErrorRoute.value);
}
</script>

<template>
  <LauncherWindow
    v-if="!isSettingsWindow"
    :query="query"
    :executing="executing"
    :execution-feedback-message="executionFeedbackMessage"
    :execution-feedback-tone="executionFeedbackTone"
    :search-shell-style="searchShellStyle"
    :staging-expanded="stagingExpanded"
    :drawer-open="drawerOpen"
    :drawer-viewport-height="drawerViewportHeight"
    :drawer-floor-viewport-height="drawerFloorViewportHeight"
    :drawer-filler-height="drawerFillerHeight"
    :keyboard-hints="keyboardHints"
    :filtered-results="filteredResults"
    :active-index="activeIndex"
    :staged-feedback-command-id="stagedFeedbackCommandId"
    :staged-commands="stagedCommands"
    :staging-drawer-state="stagingDrawerState"
    :staging-hints="stagingHints"
    :staging-list-should-scroll="stagingListShouldScroll"
    :staging-list-max-height="stagingListMaxHeight"
    :focus-zone="focusZone"
    :staging-active-index="stagingActiveIndex"
    :pending-command="pendingCommand"
    :pending-args="pendingArgs"
    :pending-arg-values="pendingArgValues"
    :pending-submit-hint="pendingSubmitHint"
    :pending-submit-mode="pendingSubmitMode"
    :safety-dialog="safetyDialog"
    :nav-current-page="navCurrentPage"
    :nav-can-go-back="navCanGoBack"
    :nav-push-page="navPushPage"
    :nav-pop-page="navPopPage"
    :nav-reset-to-search="navResetToSearch"
    :nav-stack="navStack"
    :set-search-shell-ref="setSearchShellRef"
    :set-search-input-ref="setSearchInputRef"
    :set-drawer-ref="setDrawerRef"
    :set-staging-panel-ref="setStagingPanelRef"
    :set-staging-list-ref="setStagingListRef"
    :set-result-button-ref="setResultButtonRef"
    :set-param-input-ref="setParamInputRef"
    @query-input="onQueryInput"
    @stage-result="stageResult"
    @execute-result="executeResult"
    @toggle-staging="toggleStaging"
    @staging-drag-start="onStagingDragStart"
    @staging-drag-over="onStagingDragOver"
    @staging-drag-end="onStagingDragEnd"
    @focus-staging-index="onFocusStagingIndex"
    @remove-staged-command="removeStagedCommand"
    @update-staged-arg="updateStagedArg"
    @clear-staging="clearStaging"
    @execute-staged="executeStaged"
    @submit-param-input="submitParamInput"
    @cancel-param-input="cancelParamInput"
    @arg-input="updatePendingArgValue"
    @confirm-safety-execution="confirmSafetyExecution"
    @cancel-safety-execution="cancelSafetyExecution"
    @blank-pointerdown="hideMainWindow"
    @execution-feedback="setExecutionFeedback"
  />

  <SettingsWindow
    v-else
    :settings-nav-items="settingsNavItems"
    :settings-route="settingsRoute"
    :settings-error-route="settingsErrorRoute"
    :hotkey-global-fields="hotkeyGlobalFields"
    :hotkey-search-fields="hotkeySearchFields"
    :hotkey-queue-fields="hotkeyQueueFields"
    :get-hotkey-value="getHotkeyValue"
    :is-hotkey-recording="isHotkeyRecording"
    :get-hotkey-display="getHotkeyDisplay"
    :hotkey-error-fields="hotkeyErrorFields"
    :hotkey-error-primary-field="hotkeyErrorPrimaryField"
    :hotkey-error-message="hotkeyErrorMessage"
    :available-terminals="availableTerminals"
    :terminal-loading="terminalLoading"
    :terminal-dropdown-open="terminalDropdownOpen"
    :terminal-focus-index="terminalFocusIndex"
    :default-terminal="defaultTerminal"
    :language="language"
    :auto-check-update="autoCheckUpdate"
    :launch-at-login="launchAtLogin"
    :selected-terminal-option="selectedTerminalOption"
    :selected-terminal-path="selectedTerminalPath"
    :language-options="languageOptions"
    :app-version="appVersion"
    :runtime-platform="runtimePlatform"
    :update-status="updateStatus"
    :command-rows="commandRows"
    :command-summary="commandSummary"
    :command-load-issues="commandLoadIssues"
    :command-filtered-count="commandFilteredCount"
    :command-view="commandView"
    :command-source-options="commandSourceOptions"
    :command-status-options="commandStatusOptions"
    :command-category-options="commandCategoryOptions"
    :command-override-options="commandOverrideOptions"
    :command-issue-options="commandIssueOptions"
    :command-sort-options="commandSortOptions"
    :command-display-mode-options="commandDisplayModeOptions"
    :command-source-file-options="commandSourceFileOptions"
    :command-groups="commandGroups"
    :settings-error="settingsError"
    :settings-saved="settingsSaved"
    :close-confirm-open="settingsCloseConfirmOpen"
    :window-opacity="windowOpacity"
    :theme="theme"
    :blur-enabled="blurEnabled"
    :themes="themes"
    @update-hotkey="applyHotkeyChange"
    @navigate="navigateSettings"
    @toggle-terminal-dropdown="toggleTerminalDropdown"
    @select-terminal="selectTerminalOption"
    @select-language="selectLanguageOption"
    @set-auto-check-update="setAutoCheckUpdate"
    @set-launch-at-login="setLaunchAtLogin"
    @toggle-command-enabled="toggleCommandEnabled"
    @set-filtered-commands-enabled="setFilteredCommandsEnabled"
    @update-command-view="updateCommandView"
    @reset-command-filters="resetCommandFilters"
    @update-opacity="setWindowOpacity"
    @update-theme="setTheme"
    @update-blur-enabled="setBlurEnabled"
    @check-update="checkUpdate"
    @download-update="downloadUpdate"
    @open-homepage="openHomepage"
    @close="closeSettingsWindow"
    @apply="saveSettings"
    @confirm="confirmSettings"
    @navigate-to-error="navigateToSettingsError"
    @cancel-close-confirm="cancelSettingsCloseConfirm"
    @discard-close-confirm="
      () => {
        discardUnsavedSettingsChanges();
        closeSettingsWindow();
      }
    "
  />
</template>
